/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/settings/secrets`; params?: Router.UnknownInputParams; } | { pathname: `/settings/triggers`; params?: Router.UnknownInputParams; } | { pathname: `/settings/blueprints`; params?: Router.UnknownInputParams; } | { pathname: `/settings/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/settings/appearance`; params?: Router.UnknownInputParams; } | { pathname: `/conversation/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/settings/secrets/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/settings/triggers/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/settings/blueprints/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/settings/tasks/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/secrets`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/triggers`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/blueprints`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/appearance`; params?: Router.UnknownOutputParams; } | { pathname: `/conversation/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/settings/secrets/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/settings/triggers/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/settings/blueprints/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/settings/tasks/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/settings/secrets${`?${string}` | `#${string}` | ''}` | `/settings/triggers${`?${string}` | `#${string}` | ''}` | `/settings/blueprints${`?${string}` | `#${string}` | ''}` | `/settings/tasks${`?${string}` | `#${string}` | ''}` | `/settings/appearance${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/settings/secrets`; params?: Router.UnknownInputParams; } | { pathname: `/settings/triggers`; params?: Router.UnknownInputParams; } | { pathname: `/settings/blueprints`; params?: Router.UnknownInputParams; } | { pathname: `/settings/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/settings/appearance`; params?: Router.UnknownInputParams; } | `/conversation/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/settings/secrets/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/settings/triggers/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/settings/blueprints/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/settings/tasks/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/conversation/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/settings/secrets/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/settings/triggers/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/settings/blueprints/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/settings/tasks/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
