/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/blueprints`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/todos`; params?: Router.UnknownInputParams; } | { pathname: `/triggers`; params?: Router.UnknownInputParams; } | { pathname: `/secrets`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/blueprint/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/conversation/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/todo/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/trigger/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/secret/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/blueprints`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/todos`; params?: Router.UnknownOutputParams; } | { pathname: `/triggers`; params?: Router.UnknownOutputParams; } | { pathname: `/secrets`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/blueprint/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/conversation/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/todo/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/trigger/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/secret/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/blueprints${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/todos${`?${string}` | `#${string}` | ''}` | `/triggers${`?${string}` | `#${string}` | ''}` | `/secrets${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/blueprints`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/todos`; params?: Router.UnknownInputParams; } | { pathname: `/triggers`; params?: Router.UnknownInputParams; } | { pathname: `/secrets`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/blueprint/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/conversation/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/todo/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/trigger/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/secret/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/blueprint/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/conversation/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/todo/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/trigger/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/secret/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
