import { compile } from 'json-schema-to-typescript';

type GenerateTypesOptions = {
  url: string;
  prefix?: string;
};

type GenerateTypesResult = {
  code: string;
};

const generateTypes = async (options: GenerateTypesOptions): Promise<GenerateTypesResult> => {
  const prefix = options.prefix ?? '/api';
  const schemaUrl = new URL(`${prefix}/schema`, options.url);
  const schemaResponse = await fetch(schemaUrl);

  if (!schemaResponse.ok) {
    throw new Error(`Failed to fetch schema: ${schemaResponse.status} ${schemaResponse.statusText}`);
  }

  const schemaData = (await schemaResponse.json()) as Record<string, unknown>;

  const compiled = await compile(schemaData, 'Schema', {
    additionalProperties: false,
    bannerComment:
      '/* eslint-disable */\n// Auto-generated by @morten-olsen/agentic-client generator\n// Do not edit manually',
  });

  const code =
    compiled +
    '\n' +
    'type ServerDefinition = {\n' +
    '  tools: Schema["tools"];\n' +
    '  events: Schema["events"];\n' +
    '};\n' +
    '\n' +
    'export type { ServerDefinition };\n';

  return { code };
};

export type { GenerateTypesOptions, GenerateTypesResult };
export { generateTypes };
